dist: xenial
language: python
python: 3.7

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pytest-cov
  - pip install codacy-coverage
  - pip install -e .

script:
  - pytest --cov=mabe_converters
  - coverate xml
  - python-codacy-coverage -r coverage.xml